### ISSUE TITLE
docker build is failing due to dependency change

### ISSUE THREAD

**Issue by pondersome** [Dave-van-der-Meer/leorover_gazebo_sim_docker#5]
I'm getting an error  running bash docker_build.sh:

ERROR [14/16] RUN git clone -b ros2 --single-branch https://github.com/ros/sdformat_urdf.git
> [14/16] RUN git clone -b ros2 --single-branch https://github.com/ros/sdformat_urdf.git:
0.277 Cloning into 'sdformat_urdf'...
0.516 warning: Could not find remote branch ros2 to clone.
0.516 fatal: Remote branch ros2 not found in upstream origin

It seems the ros2 branch no longer exists in sdformat_urdf. It was probably renamed. Do you have a suggestion for the proper branch or commit to pull from this repo?

FYI, I've tried both the humble and iron branches and they both seem to pull fine. I'm getting a different error after that change, but it seems unrelated so I'll create a separate issue.

Thank you!

**Comment by Dave-van-der-Meer** [comment]
Issue fixed with PR https://github.com/Dave-van-der-Meer/leorover_gazebo_sim_docker/pull/7
Thanks for your contribution :smiley:
