### ISSUE TITLE
docker build failing on colcon build of ros_gz_bridge

### ISSUE THREAD

**Issue by pondersome** [Dave-van-der-Meer/leorover_gazebo_sim_docker#6]
This seems like a very exciting learning platform and I hope to get it working asap.

But I'm clueless as to  why this might be happening, and it's preventing the image from being built:

 => ERROR [16/16] RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build --symlink-install --executor sequential"        59.6s
------                                                                                                                                    
 > [16/16] RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build --symlink-install --executor sequential":                    
0.815 Starting >>> ros_gz_interfaces                                                                                                      
38.37 Finished <<< ros_gz_interfaces [37.6s]                                                                                              
38.37 Starting >>> ros_gz_sim                                                                                                             
56.68 Finished <<< ros_gz_sim [18.3s]                                                                                                     
56.68 Starting >>> sdformat_test_files
57.11 Finished <<< sdformat_test_files [0.42s]
57.69 Starting >>> ros_gz_bridge
60.06 --- stderr: ros_gz_bridge
60.06 CMake Error at CMakeLists.txt:92 (find_package):
60.06   By not providing "Findvision_msgs.cmake" in CMAKE_MODULE_PATH this project
60.06   has asked CMake to find a package configuration file provided by
60.06   "vision_msgs", but CMake did not find one.
60.06 
60.06   Could not find a package configuration file provided by "vision_msgs" with
60.06   any of the following names:
60.06 
60.06     vision_msgsConfig.cmake
60.06     vision_msgs-config.cmake
60.06 
60.06   Add the installation prefix of "vision_msgs" to CMAKE_PREFIX_PATH or set
60.06   "vision_msgs_DIR" to a directory containing one of the above files.  If
60.06   "vision_msgs" provides a separate development package or SDK, be sure it
60.06   has been installed.
60.06 
60.06 
60.06 ---
60.06 Failed   <<< ros_gz_bridge [2.36s, exited with code 1]

**Comment by Dave-van-der-Meer** [comment]
Issue fixed with PR https://github.com/Dave-van-der-Meer/leorover_gazebo_sim_docker/pull/7
Thanks for your contribution :smiley:
